# Project Name
TARGET = lowstepper_daisy_firmware

# Sources
CPP_SOURCES = lowstepper_daisy_firmware.cpp

# Library Locations
LIBDAISY_DIR = ../../DaisyExamples/libdaisy/
DAISYSP_DIR = ../../DaisyExamples/daisysp/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
